# Node.js 버전 v21.7.1을 사용하는 베이스 이미지 설정
FROM node:21

# 작업 디렉토리를 설정합니다.
WORKDIR /usr/src/app

# package.json과 package-lock.json을 복사합니다.
COPY package*.json ./

# 프로젝트의 의존성을 설치합니다.
RUN yarn

# 소스 코드를 모두 복사합니다.
COPY . .

# 포트를 설정합니다. NestJS 기본 포트는 3000입니다.
EXPOSE 3000

# 개발 모드로 애플리케이션을 실행합니다.
CMD ["npm", "run", "start:dev"]
