version: '3'
services:
  ngrok1:
    image: wernight/ngrok
    command: sh -c 'ngrok config add-authtoken YOUR_NGROK_AUTH_TOKEN && ngrok http https://host.docker.internal:8080'
    ports:
      - "4040:4040" # ngrok web interface
    platform: linux/amd64
    container_name: n1

  ngrok2:
    image: wernight/ngrok
    command: sh -c 'ngrok config add-authtoken YOUR_NGROK_AUTH_TOKEN && ngrok http http://host.docker.internal:30002'
    ports:
      - "4041:4040" # ngrok web interface for second tunnel
    platform: linux/amd64
    container_name: n2
