apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: post:latest  # 여기서 "post:latest"는 빌드된 Docker 이미지 이름입니다.
          imagePullPolicy: Never  # 이미지를 풀링하지 않도록 설정
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              value: "development"
