name: Build and Deploy to Argo CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t post:latest .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.5.0/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to Argo CD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_URL }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login --insecure $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD

      - name: Update Argo CD Application Image
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_URL }}
        run: |
          argocd app set post --image post:latest
          argocd app sync post --server $ARGOCD_SERVER
